<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../engine/processNewVisitForm.php';

/**
 * Test class for processNewVisitForm.
 * Generated by PHPUnit on 2010-05-10 at 10:59:30.
 */
class processNewVisitFormTest extends PHPUnit_Framework_TestCase {
    /**
     * @var processNewVisitForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new processNewVisitForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddToDb().
     */
    public function testAddToDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
