<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../forms/testForm.php';

/**
 * Test class for testForm.
 * Generated by PHPUnit on 2010-05-10 at 10:52:19.
 */
class testFormTest extends PHPUnit_Framework_TestCase {
    /**
     * @var testForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new testForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
}
?>
